name: Create TAG

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      VersionCode:
        required: true
        type: string
      VersionName:
        required: true
        type: string
      CleanVersion:
        required: true
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.event }}-${{ github.ref }}
  cancel-in-progress: true        

jobs:

  CreateTAG:
    name: Create Tag of Version
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Get Version Code and Name of App
        id: getVersion
        run: |
          VERSION_CODE=$(grep -m 1 'versionCode' app/build.gradle | awk '{print $2}')
          VERSION_NAME=$(grep -m 1 'versionName' app/build.gradle | awk -F '"' '{print $2}')
          CLEAN_VERSION=$(echo "$VERSION_NAME" | awk '{print $2}')
          echo "VersionCode=$VERSION_CODE" >> $GITHUB_OUTPUT
          echo "VersionName=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "CleanVersion=$CLEAN_VERSION" >> $GITHUB_OUTPUT

      - name: Create and Push Tag
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.name "Action Finances"
          git config --local user.email "actions-finances@japl.dev"
          git tag "v${{ steps.getVersion.outputs.VersionCode }}" -m "Release v${{ steps.getVersion.outputs.VersionName }}"
          git push origin "v${{ steps.getVersion.outputs.CleanVersion }}"
 
