name: Deploy Workflow
on:
  workflow_call:
    secrets:
      GOOGLE_PLAY_SERVICE_ACCOUNT:
        required: true
    inputs:
      environment:
        required: true
        type: string
      VersionCode:
        required: true
        type: string
      VersionName:
        required: true
        type: string
      CleanVersion:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - uses: actions/checkout@v4
    
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download aab
        uses: actions/download-artifact@v4
        with:
          path: ./
          name: aab-file

      - name: Check Files
        run: ls -lnR

      - name: Upload to Play Store
        if: github.ref == 'refs/heads/master'
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: co.japl.android.myapplication
          releaseFiles: ./app-release.aab
          track: internal
          inAppUpdatePriority: 0
          status: completed
