name: Lint Workflow
on:
  workflow_call:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Run Lint
        run: ./gradlew lintDebug --no-daemon --no-parallel --stacktrace

      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path:  |
                ./app/build/reports/
                ./build/reports
                ./japl-android-about-module/build/reports
                ./ui/build/intermediates/lint_intermediate_text_report/debug
                ./japl-android-finances-services/build/reports
                ./model/build/reports
                ./japl-android-graphs/build/reports
                ./japl-finances-iport/build/reports
                ./japl-android-finances-core/build/reports
                ./japl-android-finances-paid-module/build/reports
                ./japl-android-finances-inputs/build/reports
                ./credit/build/reports
                ./CreditCardModule/build/reports
