name: Merge and Deploy App
description: Pull code, Merge it, prepared app and deploy into Play Store

on:
  workflow_dispatch:

jobs:

  prepared_project:
    environment: PROD
    runs-on: ubuntu-latest
    outputs:
      VersionCode: ${{ steps.getVersion.outputs.VersionCode }}
      VersionName: ${{ steps.getVersion.outputs.VersionName }}

    steps:

      - uses: actions/checkout@v4

      - name: Get Version Code and Name of App
        id: getVersion
        run: |
              VERSION_CODE=$(grep -m 1 'versionCode' app/build.gradle | awk '{print $2}')
              VERSION_NAME=$(grep -m 1 'versionName' app/build.gradle | awk -F '"' '{print $2}')
              echo "VersionCode=$VERSION_CODE" >> $GITHUB_OUTPUT
              echo "VersionName=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Remove Android Folder
        run: |
              rm -rf about-module
        shell: bash
        
      - name: Get About Module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-about-module
          path: ./about-module
      
      - name: Build and Scan
        continue-on-error: true
        run: ./gradlew bundleRelease --no-daemon --no-parallel --info
