name: Lint, Test, and Deploy App
description: Run lint, tests, then pull code, merge it, prepare app, and deploy to Play Store

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: [test]
    uses: ./.github/workflows/build.yml
    with:
      environment: PROD
    secrets:
      SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    secrets:
      GOOGLE_PLAY_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
    with:
      VersionCode: ${{ needs.build.outputs.VersionCode }}
      VersionName: ${{ needs.build.outputs.VersionName }}
      CleanVersion: ${{ needs.build.outputs.CleanVersion }}

  createtag:
    needs: [deploy]
    uses: ./.github/workflows/createtag.yml
    with:
      VersionCode: ${{ needs.build.outputs.VersionCode }}
      VersionName: ${{ needs.build.outputs.VersionName }}
      CleanVersion: ${{ needs.build.outputs.CleanVersion }}
