name: Lint, Test, and Deploy App
description: Run lint, tests, then pull code, merge it, prepare app, and deploy to Play Store

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    needs: [lint]
    if: always()
    uses: ./.github/workflows/test.yml

  build:
    needs: [test]
    uses: ./.github/workflows/build.yml
    secrets:
      SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    secrets:
      GOOGLE_PLAY_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
    with:
      VersionCode: ${{ needs.build.outputs.VersionCode }}
      VersionName: ${{ needs.build.outputs.VersionName }}
      CleanVersion: ${{ needs.build.outputs.CleanVersion }}
