name: Test Workflow
on:
  workflow_call:
    outputs:
      error_log:
        description: "Test error log"
        value: ${{ jobs.test.outputs.error_log }}

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    outputs:
      error_log: ${{ steps.error_log.outputs.log_content }}
    steps:

      - uses: actions/checkout@v4
      
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Run Unit Tests
        id: run_tests
        run: |
          set -o pipefail
          ./gradlew testDebugUnitTest -x :about-module --no-daemon --no-parallel --stacktrace | tee build_errors.log

      - name: Read Error Log
        if: failure()
        id: error_log
        run: |
          if [ -f build_errors.log ]; then
            ERROR_CONTENT=$(tail -n 50 build_errors.log)
          else
            ERROR_CONTENT="No build_errors.log file found."
          fi
          echo "log_content<<EOF" >> "$GITHUB_OUTPUT"
          echo "$ERROR_CONTENT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: app/build/reports/tests/testDebugUnitTest/
