name: Test Run Workflow with triggers

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - feature/*
      - fea/*
      - feat/*
concurrency:
  group: ${{ github.workflow }}-${{ github.event }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
   uses: ./.github/workflows/build.yml
   with:
      environment: PROD
   secrets:
      SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
