name: Test Workflow
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - feature/*
      - fea/*
      - feat/*
concurrency:
  group: ${{ github.workflow }}-${{ github.event }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon --no-parallel --stacktrace

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: app/build/reports/tests/testDebugUnitTest/
